# Generated by Django 3.1.7 on 2021-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrailStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(unique=True)),
                ('directions', models.TextField()),
                ('clue', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
    ]
