# Generated by Django 3.1.7 on 2021-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0003_auto_20210405_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailstep',
            name='hint',
            field=models.TextField(blank=True),
        ),
    ]
